# Generated by Django 4.0.6 on 2022-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='origin',
            field=models.CharField(choices=[('USA', 'UNITED STATES'), ('EUR', 'EUROPE'), ('UKR', 'UKRINE')], default='UKR', max_length=3),
        ),
    ]
