# Generated by Django 4.0.6 on 2022-08-07 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_book_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_mail',
            field=models.EmailField(blank=True, default='author2022@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
