# Generated by Django 4.0.6 on 2022-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hero', models.CharField(blank=True, max_length=40, null=True)),
                ('type_hero', models.CharField(blank=True, max_length=40, null=True)),
                ('age_hero', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='hero',
            field=models.ManyToManyField(null=True, to='book_app.hero'),
        ),
    ]
