# Generated by Django 4.0.6 on 2022-08-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_hero_book_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='hero',
            field=models.ManyToManyField(to='book_app.hero'),
        ),
    ]
